"""finalised

Revision ID: fdb6af3c04ce
Revises: 
Create Date: 2022-11-21 23:26:09.376755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb6af3c04ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_code', sa.Integer(), nullable=True),
    sa.Column('s_name', sa.String(length=200), nullable=True),
    sa.Column('s_id', sa.String(length=200), nullable=True),
    sa.Column('date', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('class_code', sa.Integer(), nullable=True),
    sa.Column('s_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('s_id')
    )
    op.create_index(op.f('ix_students_class_code'), 'students', ['class_code'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_students_class_code'), table_name='students')
    op.drop_table('students')
    op.drop_table('attendance')
    # ### end Alembic commands ###
